---
new_page_extension: md
auto_deploy: false
admin_path: static/admin
webhook_url: 
sections:
- type: heading
  label: Content
- type: directory
  path: src/pages
  label: Pages
  create: documents
  match: "*.md"
  new_doc_ext: md
  templates:
  - page
  - blocks-page
- type: directory
  path: src/pages/posts
  label: Posts
  create: documents
  match: "**/*"
  new_doc_ext: md
  templates:
  - post
- type: heading
  label: Config
- type: document
  path: src/data/main_menu.json
  label: Nav Menu
- type: document
  path: src/data/sub_1_menu.json
  label: Sub Menu 1
- type: document
  path: src/data/sub_2_menu.json
  label: Sub Menu 2
- type: document
  path: site-config.json
  label: Site Config
upload_dir: static/images
public_path: "/images"
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
build:
  preview_env:
  - FIREBASE_SERVICE_ACCOUNT=/MIIEvgIBADANBgkqhkiG9w0BAQEFAASCBKgwggSkAgEAAoIBAQCjWBLRYzAGGCwh\nMi4JLDLNugwkkV5U9XR3NgX4MS5M7B0rAQOEQDCy4TJqomQzDOrBdPaCYNVdUyex\nPNCeTS8BJ4JxYRb1IhwK4ThW0OwiaNV1w+S3hwv8iX+p4Qvft42Uj/C9llR97dQK\n79+5gnCr/CP4FmM8PXztjlbixuku97WIT2V9EPY+ae5p6VBfYVcGpxboCesYFZBD\noFpH93iiPZxb0xk3LvSCiFAK1QumDdYWjxXCquvamNJzRhN2BvM/p+yapaAIdzXA\nYNUreWwixhk5pBTV4fCaT5KR5frK1BUIquC+ihGyWBgVsanyZrHYyoCk22npdad2\n/oqAyfBRAgMBAAECggEABsCQqZNvNCdKZrZlcQdg08CHuTjBpKMvZPCoo0N8MZ2W\nkJUmhTBmmvRkckRDflk/uI7KVGYml8ik1Map7ItOAL8WfTOZYHmAHYKFItCY3EzH\nWyqFgUEtwYsZCgeVpzI2IfCnz9x/omODDw8uqUNfPzrJbVtWj5JOoF7QkGgO0lxF\n2UhzescAS5Dom3duMeXDffVEgJEzAQPTKWMH95JY877aGksHR8dDyB7ezNule44x\n9RC0bxg21KuFr1dgsdhEqHAUh4R0zUYfIoffcWGzKZLKd13JfM2PGLOZu3XTUDAG\nDmhYyWNAgQVgSFCvNA4qAqK2I+IFeqV/HJbrDG+1gQKBgQDW6zx+hlwJCuCNaagA\nqqDWURk7zMxol4Q6RDfXJnBUI+4M9sgX3H3oq2xvOJvZqdq4vKgVGwp+9vkVPMnt\n+BDgVYIiskyC65aN6kT5DjXqKlKmcfLHSB8U8vfnvK3Q4+1f0z4ESVo8ve0axXvp\nml82TTK8VuhElRXPqQPGJKWawQKBgQDCkReB9j92PKvvoUuhrGqqAaJFSaRijehi\njrFAiZK3S4y/m+61cgcXKrwdUu5nxPlRUpxi/AVOadtbF5pGeTpn2Lnjyka6UdZy\naI1sFutEti27B9TApwvOY0yF6jQoPz8JvcqVEWJZk7OLjuMgCIYZrcFv1xtCp5Fw\nxdacBiyJkQKBgQC4D2iUt38U43LiyUzvnTH3uibRNxkMrk65E/l60lm7RbY29hbx\nkI1oeX95VVLsO/Ks6i1NPgZkLCGwVYpeumfBqJm2G1s5eIhM7Ai7/7ae4DY+hDI3\nB4ZPC7LSjZ2S29FMkv5271dP1By/I8h2jRXjzIOaFxf+vGucmBQ6WuJVQQKBgQCK\nt7Ff6jYi0WzwQzpOAURnAxUzeyalUXGeWwfK8IrW/hlSPxV47dxaSxClg4wQFeJ/\ndXukIvSRjG1lS7Wliyb2BRG7c2rryg8vsJUrvEduzMhb8WBhHngPZMKZM3qOO1Fx\nW4xErYlGPkUjOfN60jjxs+0XFPENm7TZB2RUBx7X0QKBgCGN+MQfnSigGx9tzo70\nvZOQfJMGwSxSB4fzmgNED0CsCGQprepEbU/XN/8oj9FTqYk8lwRK6IxSJgvu8NB0\nLkMJoIcdmTs9UrtiNAWeSMzjPolFCFR0/lc0QAouqljqjsQRsSAlt1lHL2eE89WK\nhJLxQkc08OJpClI3wUlh3yHx
  preview_output_directory: public
  install_dependencies_command: npm install
  preview_docker_image: node:10
  mount_path: "/srv"
  working_dir: "/srv"
  instant_preview_command: npm run forestry:preview
