---
label: Site Config
hide_body: false
fields:
- type: select
  name: type
  config:
    source:
      type: simple
    options:
    - internal
    - external
  label: Type
  default: internal
- name: title
  label: Title
  type: text
  hidden: false
  default: ''
- name: description
  label: Description
  type: textarea
  hidden: false
  default: ''
- name: footer
  label: Footer
  type: textarea
  config:
    wysiwyg: true
    schema:
      format: html-blocks
  hidden: false
  default: ''
